### ISSUE TITLE
Add more properties

### ISSUE THREAD

**Issue by btopro** [dtn9197/herocard#6]
https://github.com/dtn9197/herocard/blob/82d0fcc80d1a688b33c0d15c22ab183f71f2cccc/herocard.js#L39-L44

Find other relevent ones for a baseball card style mock up. Maybe a universe for DC vs Marvel and then applying a logo that matches the universe or supporting a `sticker` to be more generic and then the sticker is just applies via a png file (like dc / marvel).

**Comment by dtn9197** [comment]
added 2 more properties: one for the hero image and one for the logo image of the universe they're in.
